## Deep Learning Project -- Data Cleaning

In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("wind_dataset.csv")

In [3]:
data.columns

Index(['DATE', 'WND', 'TMP', 'AA1', 'AO1', 'CF1', 'CF2', 'CF3', 'CH1', 'CI1',
       'CT1', 'CT2', 'CT3', 'CU1', 'CU2', 'CU3', 'CV1', 'CV2', 'CV3', 'CW1',
       'GH1', 'IB2', 'KA1', 'KA2', 'OB1'],
      dtype='object')

In [4]:
# splitting dataframe on column for all columns
def data_process(data):
    # wnd columns -- 5 min direction, direction quality, type, speed, speed quality
    data[["wnd_direct", "wnd_qual", "wnd_type", "wnd_speed", "wnd_qual"]] = data.WND.str.split(",", expand=True)
    data.drop(["wnd_direct", "wnd_qual", "wnd_type"], axis=1, inplace=True)

    # tmp columns -- 5 min temperature of air, temperature quality
    data[["temp_change", "temp_qual"]] = data.TMP.str.split(",", expand=True)
    data.drop(["temp_qual"],axis=1,inplace=True)

    # AA1 columns -- HOURLY liquid perciptation occurence identifier -- period quantity, depth dimension,condition code, quality code
    data[["hourly_liq_per_quant", "hourly_liq_depth_dim" ,"hourly_liq_cond", "hourly_liq_qual"]] = data.AA1.str.split(",", expand=True)
    data.drop(["hourly_liq_cond", "hourly_liq_qual"], axis=1,inplace=True)

    # AO1 columns -- 5 min perciptation occurnence identifier -- period quantity, depth dimension,condition code, quality code
    data[["liq_per_quant", "liq_depth_dim" ,"liq_cond", "liq_qual"]] = data.AO1.str.split(",", expand=True)
    data.drop(["liq_cond", "liq_qual"],axis=1, inplace=True)

    # CF1 columns -- HOURLY fan speed section 1
    data[["fan_speed", "fan_quality", "fan_quality_code"]] =  data.CF1.str.split(",", expand=True)
    data.drop(["fan_quality", "fan_quality_code"],axis=1, inplace=True)

    # CF2 columns -- HOURLY fan speed section 2
    data[["fan_speed2", "fan_quality2", "fan_quality_code2"]] =  data.CF2.str.split(",", expand=True)
    data.drop(["fan_quality2", "fan_quality_code2"], axis=1, inplace=True)

    # CF3 columns -- HOURLY fan speed section 3
    data[["fan_speed3", "fan_quality3", "fan_quality_code3"]] =  data.CF3.str.split(",", expand=True)
    data.drop([ "fan_quality3", "fan_quality_code3"], axis=1, inplace=True)

    # CH1 columns -- 5min RELATIVE HUMIDITY/TEMPERATURE period quantity -- average air temperature, quality code
    # quality code, average relative humidity, quality code, AVG_RH_FLAG quality code
    data[["rh_period_quantity","rh_air_temp", "rh_airtemp_qual", "rh_airtemp_qual_flag", "rel_humiditiy", "rel_humidity_qual", "rel_humidity_qual_flag"]] =  data.CH1.str.split(",", expand=True)
    data.drop(["rh_airtemp_qual", "rh_airtemp_qual_flag","rel_humidity_qual", "rel_humidity_qual_flag"], axis=1, inplace=True)


    # CI1 columns -- HOURLY Relative Humidity and 
    data[["min_hourly_air_temp", "min_hourly_airtemp_qual", "min_hourly_airtemp_flag", 
          "max_hourly_air_temp", "max_hourly_airtemp_qual", "max_hourly_airtemp_flag",
          "std_hourly_air_temp", "std_hourly_airtemp_qual", "std_hourly_airtemp_flag",
          "std_hourly_humidity", "std_hourly_humidity_qual", "std_hourly_humidity_flag"]] =  data.CI1.str.split(",", expand=True)
    data.drop(["min_hourly_airtemp_qual", "min_hourly_airtemp_flag", 
               "max_hourly_airtemp_qual", "max_hourly_airtemp_flag",
               "std_hourly_airtemp_qual", "std_hourly_airtemp_flag",
               "std_hourly_humidity_qual", "std_hourly_humidity_flag"], axis=1, inplace=True)


    # CT1 columns -- 5 min Temperature Section -- sensor 1
    data[["air_temp", "air_temp_qual", "air_temp_flag"]] =  data.CT1.str.split(",", expand=True)
    data.drop(["air_temp_qual", "air_temp_flag"],axis=1, inplace=True)


    # CT2 columns -- 5 min Temperature Section -- sensor 2
    data[["air_temp_2", "air_temp_qual_2", "air_temp_flag_2"]] =  data.CT2.str.split(",", expand=True)
    data.drop(["air_temp_qual_2", "air_temp_flag_2"], axis=1, inplace=True)

    # CT3 columns -- 5 min Temperature Section -- sensor 3
    data[["air_temp_3", "air_temp_qual_3", "air_temp_flag_3"]] =  data.CT3.str.split(",", expand=True)
    data.drop(["air_temp_qual_3", "air_temp_flag_3"],axis=1, inplace=True)


    # CU1 columns -- HOURLY Temperature Section -- sensor 1
    data[["hourly_air_temp", "hourly_air_temp_qual", "hourly_air_temp_flag",
          "std_hourly_air_temp", "std_hourly_air_temp_qual", "std_hourly_air_temp_flag"]] =  data.CU1.str.split(",", expand=True)
    data.drop(["hourly_air_temp_qual", "hourly_air_temp_flag",
               "std_hourly_air_temp_qual", "std_hourly_air_temp_flag"],axis=1, inplace=True)

    # CU2 columns -- HOURLY Temperature Section -- sensor 2
    data[["hourly_air_temp_2", "hourly_air_temp_qual_2", "hourly_air_temp_flag_2",
          "std_hourly_air_temp_2", "std_hourly_air_temp_qual_2", "std_hourly_air_temp_flag_2"]] =  data.CU2.str.split(",", expand=True)
    data.drop(["hourly_air_temp_qual_2", "hourly_air_temp_flag_2",
               "std_hourly_air_temp_qual_2", "std_hourly_air_temp_flag_2"],axis=1, inplace=True)

    # CU3 columns -- HOURLY Temperature Section -- sensor 3
    data[["hourly_air_temp_3", "hourly_air_temp_qual_3", "hourly_air_temp_flag_3",
          "std_hourly_air_temp_3", "std_hourly_air_temp_qual_3", "std_hourly_air_temp_flag_3"]] =  data.CU3.str.split(",", expand=True)
    data.drop(["hourly_air_temp_qual_3", "hourly_air_temp_flag_3",
               "std_hourly_air_temp_qual_3", "std_hourly_air_temp_flag_3"],axis=1, inplace=True)

    # CV1 columns -- HOURLY extreme temperature -- sensor 1
    data[["ex_min_hourly_air_temp", "ex_min_hourly_airtemp_qual", "ex_min_hourly_airtemp_flag", 
          "min_temp_time", "min_temp_time_qual", "min_temp_time_flag",
          "ex_max_hourly_air_temp", "ex_max_hourly_airtemp_qual", "ex_max_hourly_airtemp_flag", 
          "max_temp_time", "max_temp_time_qual", "max_temp_time_flag"]] =  data.CV1.str.split(",", expand=True)
    data.drop(["ex_min_hourly_air_temp", "ex_min_hourly_airtemp_qual", "ex_min_hourly_airtemp_flag",  
               "ex_max_hourly_air_temp", "ex_max_hourly_airtemp_qual", "ex_max_hourly_airtemp_flag",
               "min_temp_time_qual", "min_temp_time_flag",
               "max_temp_time_qual", "max_temp_time_flag"],axis=1, inplace=True)

    # CV2 columns -- HOURLY extreme temperature -- sensor 2
    data[["ex_min_hourly_air_temp_2", "ex_min_hourly_airtemp_qual_2", "ex_min_hourly_airtemp_flag_2", 
          "min_temp_time_2", "min_temp_time_qual_2", "min_temp_time_flag_2",
          "ex_max_hourly_air_temp_2", "ex_max_hourly_airtemp_qual_2", "ex_max_hourly_airtemp_flag_2", 
          "max_temp_time_2", "max_temp_time_qual_2", "max_temp_time_flag_2"]] =  data.CV2.str.split(",", expand=True)
    data.drop(["ex_min_hourly_air_temp_2", "ex_min_hourly_airtemp_qual_2", "ex_min_hourly_airtemp_flag_2",  
               "ex_max_hourly_air_temp_2", "ex_max_hourly_airtemp_qual_2", "ex_max_hourly_airtemp_flag_2",
               "min_temp_time_qual_2", "min_temp_time_flag_2",
               "max_temp_time_qual_2", "max_temp_time_flag_2"], axis=1,inplace=True)

    # CV3 columns -- HOURLY extreme temperature -- sensor 3
    data[["ex_min_hourly_air_temp_3", "ex_min_hourly_airtemp_qual_3", "ex_min_hourly_airtemp_flag_3", 
          "min_temp_time_3", "min_temp_time_qual_3", "min_temp_time_flag_3",
          "ex_max_hourly_air_temp_3", "ex_max_hourly_airtemp_qual_3", "ex_max_hourly_airtemp_flag_3", 
          "max_temp_time_3", "max_temp_time_qual_3", "max_temp_time_flag_3"]] =  data.CV3.str.split(",", expand=True)
    data.drop(["ex_min_hourly_air_temp_3", "ex_min_hourly_airtemp_qual_3", "ex_min_hourly_airtemp_flag_3",  
               "ex_max_hourly_air_temp_3", "ex_max_hourly_airtemp_qual_3", "ex_max_hourly_airtemp_flag_3",
               "min_temp_time_qual_3", "min_temp_time_flag_3",
               "max_temp_time_qual_3", "max_temp_time_flag_3"], axis=1,inplace=True)

    # CW1 -- 5 min wetness
    data[["wet1", "wet1_qual", "wet1_qual_flag",
          "wet2", "wet2_qual", "wet2_qual_flag"]] =  data.CW1.str.split(",", expand=True)
    data.drop(["wet1_qual", "wet1_qual_flag",
               "wet2_qual", "wet2_qual_flag"], axis=1,inplace=True)

    # GH1 -- HOURLY solar radiation
    data[["solar_rad", "solar_radqc", "solar_rad_flag",
          "min_solar_rad", "min_solar_radqc", "min_solar_rad_flag",
          "max_solar_rad", "max_solar_radqc", "max_solar_rad_flag",
          "std_solar_rad", "std_solar_radqc", "std_solar_rad_flag"]] =  data.GH1.str.split(",", expand=True)
    data.drop(["solar_radqc", "solar_rad_flag",
               "min_solar_radqc", "min_solar_rad_flag", 
               "max_solar_radqc", "max_solar_rad_flag",
               "std_solar_radqc", "std_solar_rad_flag"], axis=1,inplace=True)

    # IB2 -- HOURLY surface temp
    data[["surface_temp", "surface_temp_qual", "surface_temp_qual_flag",
          "std_surface_temp", "std_surface_temp_qual", "std_surface_temp_qual_flag"]] =  data.IB2.str.split(",", expand=True)
    data.drop(["surface_temp_qual", "surface_temp_qual_flag","std_surface_temp_qual", "std_surface_temp_qual_flag"], axis=1,inplace=True)

    # KA1 -- HOURLY extreme temperature -- sensor 1
    data[["ex_air_temp_period", "ex_air_temp_period_code",
          "ex_air_temp", "ex_air_temp_code"]] =  data.KA1.str.split(",", expand=True)
    data.drop(["ex_air_temp_period_code","ex_air_temp_code"], axis=1,inplace=True)

    # KA2 -- HOURLY extreme temperature -- sensor 2
    data[["ex_air_temp_period_2", "ex_air_temp_period_code_2",
          "ex_air_temp_2", "ex_air_temp_code_2"]] =  data.KA2.str.split(",", expand=True)
    data.drop(["ex_air_temp_period_code_2","ex_air_temp_code_2"], axis=1,inplace=True)

    # OB1 columns -- HOURLY Wind data 
    data[["hourly_wind_period", 
          "hourly_gust", "hourly_gust_qc", "hourly_gust_flag",
          "hourly_gust_dir", "hourly_gust_dir_qc", "hourly_dir_gust_flag",
          "wind_std", "wind_qc", "wind_flag",
          "wind_dir_std", "wind_dir_qc", "wind_dir_flag"]] =  data.OB1.str.split(",", expand=True)
    data.drop(["hourly_wind_period", 
               "hourly_gust_qc", "hourly_gust_flag",
               "hourly_gust_dir_qc", "hourly_dir_gust_flag",
               "wind_qc", "wind_flag",
               "wind_dir_qc", "wind_dir_flag"], axis=1,inplace=True)

    return data

In [5]:
data_process(data)

,DATE,WND,TMP,AA1,AO1,CF1,CF2,CF3,CH1,CI1,...,surface_temp,std_surface_temp,ex_air_temp_period,ex_air_temp,ex_air_temp_period_2,ex_air_temp_2,hourly_gust,hourly_gust_dir,wind_std,wind_dir_std
0,2020-01-01T00:00:00,"999,9,R,0023,1","+0075,1","01,0000,9,1","05,0000,9,1","0816,1,0","0959,1,0","1102,1,0","05,+0077,1,0,0412,1,0","+0077,1,0,+0091,1,0,00004,1,0,00014,1,0",...,+0081,0003,010,+0089,010,+0075,0047,999,00065,99999
1,2020-01-01T00:05:00,"999,9,9,9999,9","+0076,1",NaN,"05,0000,9,1",NaN,NaN,NaN,"05,+0077,1,0,0409,1,0",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2020-01-01T00:10:00,"999,9,9,9999,9","+0071,1",NaN,"05,0000,9,1",NaN,NaN,NaN,"05,+0073,1,0,0425,1,0",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2020-01-01T00:15:00,"999,9,9,9999,9","+0073,1",NaN,"05,0000,9,1",NaN,NaN,NaN,"05,+0073,1,0,0418,1,0",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2020-01-01T00:20:00,"999,9,9,9999,9","+0068,1",NaN,"05,0000,9,1",NaN,NaN,NaN,"05,+0070,1,0,0434,1,0",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105781,2020-12-31T23:35:00,"999,9,9,9999,9","+0065,1",NaN,"05,0000,9,1",NaN,NaN,NaN,"05,+0065,1,0,0711,1,0",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
105782,2020-12-31T23:40:00,"999,9,9,9999,9","+0063,1",NaN,"05,0000,9,1",NaN,NaN,NaN,"05,+0064,1,0,0719,1,0",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
105783,2020-12-31T23:45:00,"999,9,9,9999,9","+0062,1",NaN,"05,0000,9,1",NaN,NaN,NaN,"05,+0062,1,0,0726,1,0",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
105784,2020-12-31T23:50:00,"999,9,9,9999,9","+0061,1",NaN,"05,0000,9,1",NaN,NaN,NaN,"05,+0061,1,0,0735,1,0",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
105785,2020-12-31T23:55:00,"999,9,9,9999,9","+0060,1",NaN,"05,0000,9,1",NaN,NaN,NaN,"05,+0060,1,0,0742,1,0",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
data.drop(['WND', 'TMP', 'AA1', 'AO1', 'CF1', 'CF2', 'CF3', 'CH1', 'CI1',
       'CT1', 'CT2', 'CT3', 'CU1', 'CU2', 'CU3', 'CV1', 'CV2', 'CV3', 'CW1',
       'GH1', 'IB2', 'KA1', 'KA2', 'OB1'], axis=1, inplace=True)

In [7]:
#filtered to only the hours
hourly=data[pd.to_datetime(data.DATE).dt.minute==0]

In [8]:
#found the columns where the value never changes
drop=hourly.describe().T.query('unique==1').index

In [9]:
#dropped those columns
hourly.drop(drop,axis=1,inplace=True)

C:\Users\Cory\anaconda3\lib\site-packages\pandas\core\frame.py:3997: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

In [10]:
hourly['DATE']=pd.to_datetime(hourly.DATE)

C:\Users\Cory\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [11]:
hourly.DATE.dt.month

0          1
12         1
24         1
36         1
48         1
          ..
105726    12
105738    12
105750    12
105762    12
105774    12
Name: DATE, Length: 8784, dtype: int64

In [12]:
#changed the date to a datetime and made the hour of the day a predictor
hourly['month']=hourly.DATE.dt.month
hourly['hour']=hourly.DATE.dt.hour

C:\Users\Cory\anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\Cory\anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [13]:
hourly

,DATE,wnd_speed,temp_change,hourly_liq_depth_dim,liq_depth_dim,fan_speed,fan_speed2,fan_speed3,rh_air_temp,rel_humiditiy,...,max_solar_rad,std_solar_rad,surface_temp,std_surface_temp,ex_air_temp,ex_air_temp_2,hourly_gust,wind_std,month,hour
0,2020-01-01 00:00:00,0023,+0075,0000,0000,0816,0959,1102,+0077,0412,...,00000,00000,+0081,0003,+0089,+0075,0047,00065,1,0
12,2020-01-01 01:00:00,0018,+0063,0000,0000,0813,0957,1099,+0064,0438,...,00000,00000,+0066,0004,+0076,+0062,0056,00084,1,1
24,2020-01-01 02:00:00,0020,+0059,0000,0000,0811,0955,1096,+0060,0443,...,00000,00000,+0057,0002,+0063,+0058,0054,00087,1,2
36,2020-01-01 03:00:00,0030,+0052,0000,0000,0810,0955,1093,+0053,0483,...,00000,00000,+0056,0002,+0061,+0052,0070,00098,1,3
48,2020-01-01 04:00:00,0024,+0049,0000,0000,0808,0953,1091,+0049,0506,...,00000,00000,+0047,0002,+0054,+0046,0056,00094,1,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105726,2020-12-31 19:00:00,0019,+0113,0000,0000,0886,1019,1185,+0113,0721,...,05483,00794,+0130,0008,+0114,+0105,0034,00054,12,19
105738,2020-12-31 20:00:00,0015,+0104,0000,0000,0866,0999,1160,+0105,0714,...,04638,00913,+0140,0013,+0118,+0104,0037,00062,12,20
105750,2020-12-31 21:00:00,0013,+0098,0000,0000,0819,0957,1102,+0098,0724,...,00621,00096,+0108,0005,+0104,+0097,0036,00058,12,21
105762,2020-12-31 22:00:00,0012,+0093,0000,0000,0812,0950,1094,+0094,0728,...,00507,00186,+0099,0004,+0098,+0093,0032,00055,12,22
105774,2020-12-31 23:00:00,0011,+0080,0000,0000,0807,0945,1088,+0082,0693,...,00000,00000,+0090,0002,+0093,+0080,0033,00058,12,23

In [14]:
#set the date as the index
hourly.set_index('DATE',inplace=True)
#made the rest integers
hourly=hourly.astype('int32')

In [16]:
hourly.to_csv("wind_cleaned.csv")